#!/sbin/busybox sh

if [ "a$2" == "a" ]; then
echo "$chargecurrent";
else
chargecurrent=$2;
echo "$chargecurrent";
fi;

if [ -f /sys/devices/virtual/misc/charge_current/charge_current ]; then
case "${chargecurrent}" in
0)
echo "550 550 450" > /sys/devices/virtual/misc/charge_current/charge_current;
;;
1)
echo "650 450 450" > /sys/devices/virtual/misc/charge_current/charge_current;
;;
2)
echo "700 700 500" > /sys/devices/virtual/misc/charge_current/charge_current;
;;
3)
echo "750 750 650" > /sys/devices/virtual/misc/charge_current/charge_current;
;;
4)
echo "1200 1200 900" > /sys/devices/virtual/misc/charge_current/charge_current;
;;
*)
chargecurrent=1;
;;
esac;
fi;