#!/sbin/busybox sh

if [ "a$2" == "a" ]; then
echo "$chargecurrent";
else
chargecurrent=$2;
echo "$chargecurrent";
fi;

if [ -f /sys/kernel/charge_level/charge_level ]; then
case "${chargecurrent}" in
0)
echo "550 450" > /sys/kernel/charge_level/charge_level;
;;
1)
echo "650 450" > /sys/kernel/charge_level/charge_level;
;;
2)
echo "700 500" > /sys/kernel/charge_level/charge_level;
;;
3)
echo "750 650" > /sys/kernel/charge_level/charge_level;
;;
4)
echo "1200 900" > /sys/kernel/charge_level/charge_level;
;;
*)
chargecurrent=1;
;;
esac;
fi;