#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  exit
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
fi

SYSTEM_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;
        echo $freq_for_responsiveness > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/freq_for_responsiveness
        echo $freq_for_fast_down > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/freq_for_fast_down
        echo $sampling_rate > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/sampling_rate
		echo $sampling_down_factor > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/sampling_down_factor
		echo $up_threshold > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/up_threshold
		echo $down_differential > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/down_differential
		echo $up_threshold_at_min_freq > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/up_threshold_at_min_freq
		echo $up_threshold_at_fast_down > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/up_threshold_at_fast_down
		echo $freq_step > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/freq_step
		echo $up_threshold_diff > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/up_threshold_diff
		echo $freq_step_dec > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/freq_step_dec
		echo $cpu_up_rate > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/cpu_up_rate
		echo $cpu_down_rate > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/cpu_down_rate
		echo $up_nr_cpus > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/up_nr_cpus
		echo $hotplug_freq_1_1 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_freq_1_1
		echo $hotplug_freq_2_0 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_freq_2_0
		echo $hotplug_freq_2_1 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_freq_2_1
		echo $hotplug_freq_3_0 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_freq_3_0
		echo $hotplug_freq_3_1 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_freq_3_1
		echo $hotplug_freq_4_0 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_freq_4_0
		echo $hotplug_rq_1_1 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_rq_1_1
		echo $hotplug_rq_2_0 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_rq_2_0
		echo $hotplug_rq_2_1 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_rq_2_1
		echo $hotplug_rq_3_0 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_rq_3_0
		echo $hotplug_rq_3_1 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_rq_3_1
		echo $hotplug_rq_4_0 > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/hotplug_rq_4_0
		echo $flexrate_max_freq > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/flexrate_max_freq
		echo $flexrate_forcerate > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/flexrate_forcerate
		echo $cpu_online_bias_count > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/cpu_online_bias_count
		echo $cpu_online_bias_up_threshold > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/cpu_online_bias_up_threshold
		echo $cpu_online_bias_down_threshold > /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/cpu_online_bias_down_threshold
fi
