#!/sbin/busybox sh

if [ "a$2" != "a" ]; then

	filename=$(basename $2);

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
		if [ -f $2 ]; then
			case "$3" in
				off)
					pkill -f "gesture_set.sh";
					pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture";
					echo "0" > /sys/devices/virtual/misc/touch_gestures/gestures_enabled;
				;;
				on)
					echo "1" > /sys/devices/virtual/misc/touch_gestures/gestures_enabled;
					pkill -f "gesture_set.sh";
					pkill -f "/sys/devices/virtual/misc/touch_gestures/wait_for_gesture";
					nohup /sbin/busybox sh /data/gesture_set.sh;
				;;
			esac;
		fi;
	fi;
fi;

