#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  exit
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
fi
SYSTEM_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;
  if [ -f /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/lcdfreq_enable ];then
lcdfreq_enable_tmp="/sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/lcdfreq_enable";
if [ ! -e $lcdfreq_enable_tmp ]; then
lcdfreq_enable_tmp="/dev/null";
fi;
echo "$lcdfreq_enable" > $lcdfreq_enable_tmp;
fi;
