#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
  exit
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
fi
SYSTEM_GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;
  if [ -f /sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/max_cpu_lock ];then
max_cpu_lock_tmp="/sys/devices/system/cpu/cpufreq/$SYSTEM_GOVERNOR/max_cpu_lock";
if [ ! -e $max_cpu_lock_tmp ]; then
max_cpu_lock_tmp="/dev/null";
fi;
echo "$max_cpu_lock" > $max_cpu_lock_tmp;
fi;
