#!/sbin/busybox sh

# $1 - "supplicant_scan_interval"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$supplicant_scan_interval";
else
    supplicant_scan_interval=$2;
	echo "$supplicant_scan_interval";
fi;

case "${supplicant_scan_interval}" in
	60)
		setprop wifi.supplicant_scan_interval 60;
	;;
	120)
		setprop wifi.supplicant_scan_interval 120;
	;;
	180)
		setprop wifi.supplicant_scan_interval 180;
	;;
	240)
		setprop wifi.supplicant_scan_interval 240;
	;;
	360)
		setprop wifi.supplicant_scan_interval 360;
	;;
	*)
		supplicant_scan_interval=60;
	;;
esac;


