#!/sbin/busybox sh

	TMPFILE=$(mktemp -t);

	TESTCONNECTION=`wget http://www.google.com -O $TMPFILE &>/dev/null 2>&1`;
	if [ $? != 0 ]; then
		echo "Problem: no internet connection! connect and try again";
	else
		mount -o remount,rw /system
		wget http://winhelp2002.mvps.org/hosts.zip -O $TMPFILE &>/dev/null 2>&1;
		unzip -p $TMPFILE HOSTS > /tmp/hosts &>/dev/null 2>&1;
		mv /tmp/hosts /system/etc/hosts;
		chmod 644 /system/etc/hosts;
		echo "AD Blocker: installed to /system/etc/hosts, reboot to use.";
	fi;
