#!/sbin/busybox sh

	TMPFILE=$(mktemp -t);

		mount -o remount,rw /system
		wget http://winhelp2002.mvps.org/hosts.zip -O $TMPFILE &>/dev/null 2>&1;
		unzip -p $TMPFILE HOSTS > /tmp/hosts &>/dev/null 2>&1;
		mv /tmp/hosts /system/etc/hosts;
		chmod 644 /system/etc/hosts;
		echo "AD Blocker: installed to /system/etc/hosts, reboot to use.";
