#!/sbin/busybox sh

case "$2" in
	0)
		echo "nothnig to do";
	;;
	1)
		PROFILE=`cat /data/.siyah/.active.profile`;
		echo "1" > /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_mode;
		echo "130" > /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_cb;
		echo "133" > /sys/devices/platform/samsung-pd.2/mdnie/mdnie/mdnie/user_cr;
		sed -i "s/user_cb=[0-9]*/user_cb=130/g" /data/.siyah/$PROFILE.profile;
		sed -i "s/user_cr=[0-9]*/user_cr=133/g" /data/.siyah/$PROFILE.profile;
		echo "Color was set to default, reload ExTweaks";
	;;
	*)
		echo "need input, 0=nothing, 1=reset color";
	;;
esac;

