#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	CORTEX_CHECK=-1;
	CORTEX_CHECK=`pgrep -f "/sbin/busybox sh /sbin/ext/cortexbrain-tune.sh"`;
	if [ "1$CORTEX_CHECK" \> 10 ]; then
		echo "SERVICE ONLINE";
	else
		echo "SERVICE OFFLINE";
	fi;
)&

