#!/sbin/busybox sh

if [ -f /system/xbin/su ] && [ -f /system/app/*uper?ser.apk ]; then
	echo "You have full working ROOT Installed!";
elif [ -f /system/xbin/su ] && [ -f /system/app/SuperSU.apk ]; then
	echo "You have full working ROOT Installed!";
elif [ -f /system/xbin/su ] && [ -f /system/app/Superuser.apk ]; then
	echo "You have full working ROOT Installed!";
else
	echo "You don't have ROOT installed!";
fi;

