#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	if [ -f /system/xbin/su ]; then
			/sbin/busybox mount -o remount,rw /dev/block/mmcblk0p9 /system > /dev/null 2>&1;
			/sbin/busybox mount -t rootfs -o remount,rw rootfs;
			/sbin/busybox rm -f /system/bin/su > /dev/null 2>&1;
			/sbin/busybox rm -f /system/xbin/su > /dev/null 2>&1;
			# some roms have a busybox with su applet
			if [ -e /system/xbin/busybox ]; then
				/sbin/busybox mv /system/xbin/busybox /system/xbin/boxman > /dev/null 2>&1;
				/sbin/busybox rm -f /system/xbin/busybox > /dev/null 2>&1;
			fi

			if [ -e /system/bin/busybox ]; then
				/sbin/busybox mv /system/bin/busybox /system/bin/boxman > /dev/null 2>&1;
				/sbin/busybox rm -f /system/bin/busybox > /dev/null 2>&1;
			fi

			/sbin/busybox ln -s /sbin/busybox /system/xbin/busybox > /dev/null 2>&1;

			# I need to remove this as well for Garanti CepBank app
			if [ -e /system/xbin/which ]; then
				/sbin/busybox mv /system/xbin/which /system/xbin/waswhich-bkp > /dev/null 2>&1;
				/sbin/busybox rm -f /system/xbin/which > /dev/null 2>&1;
			fi

			# SuperUser, superuser Superuser SuperUser whatever...
			/sbin/busybox rm -rf /data/dalvik-cache/*uper?ser.apk* > /dev/null 2>&1;
			/sbin/busybox rm -rf /data/dalvik-cache/*chainfire?supersu.apk* > /dev/null 2>&1;
			/sbin/busybox rm -rf /data/dalvik-cache/?uper?u* > /dev/null 2>&1;

			/sbin/busybox rm -f /system/app/Superuser.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/SuperSU.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/*uper?ser.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/*chainfire?supersu*.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/?uper?u.apk > /dev/null 2>&1;

			/sbin/busybox rm -f /data/app/Superuse*.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /data/app/*uper?ser.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /data/app/*chainfire?supersu*.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /data/app/?uper?u.apk > /dev/null 2>&1;

			/sbin/busybox rm -rf /data/data/eu.chainfire.supersu > /dev/null 2>&1;
			/sbin/busybox rm -rf /data/data/com.noshufou.android.su > /dev/null 2>&1;

			/sbin/busybox mount -o remount,ro /dev/block/mmcblk0p9 /system > /dev/null 2>&1;
			/sbin/busybox mount -t rootfs -o remount,ro rootfs > /dev/null 2>&1;
	fi;
	pkill -f "com.noshufou.android.su" > /dev/null 2>&1;
	pkill -f "eu.chinfire.supersu" > /dev/null 2>&1;
)&

sleep 3;
if [ ! -f /system/xbin/su ]; then
	echo "ROOT REMOVED! STOCK SYSTEM!";
else
	echo "ROOT NOT REMOVED! Try again";
fi;

