#!/sbin/busybox sh
export PATH="/res/customconfig/actions/push-actions:${PATH}";

(
	if [ ! -e /system/xbin/su ]; then
		if [ ! -e /system/xbin/su ]; then
			# extract Payload with root files
			/sbin/busybox mount -o remount,rw /system > /dev/null 2>&1;
			/sbin/busybox mount -o remount,rw /;
			/sbin/busybox chmod 755 /sbin/read_boot_headers;
			eval $(/sbin/read_boot_headers /dev/block/mmcblk0p5);
			load_offset=$boot_offset;
			load_len=$boot_len;
			cd /;
			dd bs=512 if=/dev/block/mmcblk0p5 skip=$load_offset count=$load_len | tar x;

			# clean su traces
			/sbin/busybox rm -f /system/bin/su > /dev/null 2>&1;
			if [ ! -d /system/xbin ]; then
				/sbin/busybox mkdir /system/xbin > /dev/null 2>&1;
				/sbin/busybox chmod 755 /system/xbin;
			fi;

			# extract SU binary
			/sbin/busybox xzcat /res/misc/payload/su.xz > /system/xbin/su;
			/sbin/busybox chown root:root /system/xbin/su;
			/sbin/busybox chmod 6755 /system/xbin/su;
			/sbin/busybox ln -s /system/xbin/su /system/bin/su

			# clean super user old apps
			/sbin/busybox rm -f /system/app/Superuser.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/SuperSU.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/*uper?ser.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/?uper?u.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /system/app/*chainfire?supersu*.apk > /dev/null 2>&1;

			/sbin/busybox rm -f /data/app/Superuse*.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /data/app/*uper?ser.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /data/app/?uper?u.apk > /dev/null 2>&1;
			/sbin/busybox rm -f /data/app/*chainfire?supersu*.apk > /dev/null 2>&1;

			/sbin/busybox rm -rf /data/dalvik-cache/*uper?ser.apk* > /dev/null 2>&1;
			/sbin/busybox rm -rf /data/dalvik-cache/*chainfire?supersu*.apk* > /dev/null 2>&1;

			/sbin/busybox rm -rf /data/data/eu.chainfire.supersu > /dev/null 2>&1;
			/sbin/busybox rm -rf /data/data/com.noshufou.android.su > /dev/null 2>&1;

			# extract super user app
			/sbin/busybox xzcat /res/misc/payload/Superuser.apk.xz > /system/app/Superuser.apk;
			/sbin/busybox chown root:root /system/app/Superuser.apk;
			/sbin/busybox chmod 644 /system/app/Superuser.apk;

			# restore witch if exist
			if [ -e /system/xbin/waswhich-bkp ]; then
				/sbin/busybox rm -f /system/xbin/which > /dev/null 2>&1;
				/sbin/busybox mv /system/xbin/waswhich-bkp /system/xbin/which > /dev/null 2>&1;
				/sbin/busybox chmod 755 /system/xbin/which > /dev/null 2>&1;
			fi;

			if [ -e /system/xbin/boxman ]; then
				/sbin/busybox rm -f /system/xbin/busybox > /dev/null 2>&1;
				/sbin/busybox mv /system/xbin/boxman /system/xbin/busybox > /dev/null 2>&1;
				/sbin/busybox chmod 755 /system/xbin/busybox > /dev/null 2>&1;
				/sbin/busybox mv /system/bin/boxman /system/bin/busybox > /dev/null 2>&1;
				/sbin/busybox chmod 755 /system/bin/busybox > /dev/null 2>&1;
			fi;

			# delete payload and kill superuser pid
			/sbin/busybox rm -rf /res/misc/payload;
			pkill -f "com.noshufou.android.su" > /dev/null 2>&1;
			pkill -f "eu.chinfire.supersu" > /dev/null 2>&1;
		fi;

	else
		echo "You have root installed already! first remove it.";
	fi;
)&

