#!/sbin/busybox sh

TMPFILE=$(mktemp -t);

mount -o remount,rw /;

DNS1=`getprop net.rmnet0.dns1`;
DNS2=`getprop net.rmnet0.dns2`;

echo "nameserver 8.8.8.8" > /system/etc/resolv.conf;
echo "nameserver $DNS1" >> /system/etc/resolv.conf;
echo "nameserver $DNS2" >> /system/etc/resolv.conf;

TESTCONNECTION=`wget http://www.google.com -O $TMPFILE > /dev/null 2>&1`;
if [ $? != 0 ]; then
	echo "Problem: no internet connection! connect and try again";
else
	(
		ntpd -n -q -p `cat /system/etc/gps.conf | grep NTP_SERVER | cut -f 2 -d "="`;
	)&
	echo "updated time via ntp";
fi;

rm -f $TMPFILE;

